### PR TITLE
Final report **do not delete branch**

### PR DESCRIPTION
**Pull request by Lord-Left**
The purpose of this PR is to update master with the commits from final report. Once that is completed, I can update the git log in the final report and generate the final version of our final report pdf. Note that I changed the formatting for the reflections and some of the code blocks - large code blocks are super finicky in markdown, often breaking when I tried adjusting the formatting of some other part of the report. In particular, the formatting for `binarytree.ll` keep breaking whenever I tried to update the reflections section. I also generated a pdf using a custom macdown rendering profile, using the Inconsolata font. This is just to get a sense of what a pdf of our report would look like - we can change the settings of our actual final report quite easily.

### CODE REVIEW

**Comment by jkon1513** [comment]
i approved. not merging to give others a chance to leave comments.

**Comment by pattersongp** [comment]
In section 6, there are some instructions that I think should have been deleted.

**Comment by pattersongp** [comment]
In section `3.3.3.7 String Concatenation Operator` there is an inline comment in the code example that we do not support

**Comment by pattersongp** [comment]
The array lib `h` file is incorrect-- not sure where this version is from?

**Comment by pattersongp** [comment]
there is a typo in the last sentence of @jkon1513 Jason's reflection.

**Comment by Lord-Left** [comment]
@pattersongp, I'll make the requested changes. As for the inclusion of .ll/.s files, in Section 6 of Professor Edward's Final Report Outline, Edwards says we should _"Show two or three representative source language programs along with the target language program generated for each."_ It's a pretty confusing directive, and I interpreted it as "include a sample program and generated llvm output." I find that this is how other groups interpreted the directive as well, but I may be off base.

**Comment by pattersongp** [comment]
> @pattersongp, I'll make the requested changes. As for the inclusion of .ll/.s files, in Section 6 of Professor Edward's Final Report Outline, Edwards says we should _"Show two or three representative source language programs along with the target language program generated for each."_ It's a pretty confusing directive, and I interpreted it as "include a sample program and generated llvm output." I find that this is how other groups interpreted the directive as well, but I may be off base.

No you're right! My bad.

**Pull request merged**
