### PR TITLE
Adds support for printing and storing string

### PR DESCRIPTION
**Pull request by pattersongp**
```
root@2a4e46009c9f:/home/fire# cat string.fire
func int main = (int x) => {

str s = "hello world";
sprint(s);
}
root@2a4e46009c9f:/home/fire# ./comp.sh string.fire
string.fire
root@2a4e46009c9f:/home/fire# ./string.fire.exe
"hello world"
root@2a4e46009c9f:/home/fire#
```

### CODE REVIEW

**Comment by ochan4** [comment]
ill add sprint() to LRM

**Comment by jkon1513** [comment]
So were going to have a unique print function based on type?

**Comment by ochan4** [comment]
yeah we need to be explicit for print. that's our principle as well

**Comment by pattersongp** [comment]
> So were going to have a unique print function based on type?

yeah I added `sprint` because it was just easier to do that, then recursively match on the type of the expression. We could do this in the future, but for now this is a good approach

**Pull request merged**
